Repository CAPStone-CAPS/django-server, pull requests merged in 2025-08, with the labels that each got.

#7 feat: 로그인 회원가입 기능 API 구현
  apps/api/api.py
  apps/api/auth.py
  apps/users/api/__init__.py
  apps/users/api/endpoints.py
  apps/users/api/router.py
  apps/users/api/schemas.py
  config/settings/base.py
  config/urls.py
  pyproject.toml
  uv.lock
Labels: 재희, ✨ Feature

#9 feat: AI 요약 관련 API 제작
  .env.example
  .github/workflows/deploy.yaml
  .gitignore
  apps/api/admin.py
  apps/api/api.py
  apps/api/models.py
  apps/summary/__init__.py
  apps/summary/admin.py
  apps/summary/api.py
  apps/summary/apps.py
  apps/summary/migrations/0001_initial.py
  apps/summary/migrations/__init__.py
  apps/summary/models.py
  apps/summary/schema.py
  apps/summary/services/__init__.py
  apps/summary/services/gemini_service.py
  apps/summary/tests.py
  config/settings/base.py
  pyproject.toml
  uv.lock
Labels: 윤석, ✨ Feature

#12 feat: 그룹에서 투표 기능 추가
  apps/api/api.py
  apps/api/auth.py
  apps/api/schema.py
  apps/group/api/__init__.py
  apps/group/api/group.py
  apps/group/api/group_member.py
  apps/group/api/group_vote.py
  apps/group/migrations/0002_mvpvote.py
  apps/group/models.py
  apps/group/schema/__init__.py
  apps/group/schema/group.py
  apps/group/schema/group_vote.py
Labels: 윤석, ✨ Feature, 🧰 Chore

#11 feat: 사용시간 기록 및 조회 API 초기 구현
  .idea/.gitignore
  .idea/django-server.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  apps/api/api.py
  apps/usage/__init__.py
  apps/usage/admin.py
  apps/usage/api/__init__.py
  apps/usage/api/endpoints.py
  apps/usage/api/router.py
  apps/usage/api/schemas.py
  apps/usage/apps.py
  apps/usage/migrations/0001_initial.py
  apps/usage/migrations/__init__.py
  apps/usage/models.py
  apps/usage/tests.py
  apps/usage/views.py
  apps/users/__init__.py
  apps/users/admin.py
  apps/users/apps.py
  apps/users/migrations/__init__.py
  apps/users/models.py
  apps/users/tests.py
  apps/users/views.py
  config/settings/base.py
Labels: 재희, ✨ Feature

#16 feat: 프로필 이미지 등록 API 제작
  .gitignore
  apps/api/schema.py
  apps/group/api/group_member.py
  apps/group/api/group_vote.py
  apps/group/schema/group.py
  apps/group/schema/group_vote.py
  apps/users/api/endpoints.py
  apps/users/api/schemas.py
  apps/users/apps.py
  apps/users/migrations/0001_initial.py
  apps/users/models.py
  config/settings/base.py
  config/urls.py
  docker-compose.yml
  media/.gitkeep
  nginx/default.conf
  pyproject.toml
  uv.lock
Labels: 윤석, ✨ Feature

#18 feat: `username`으로 그룹 멤버 추가/제거 + AI요약에 실제 데이터를 조회하여 제공
  apps/api/schema.py
  apps/group/api/group_member.py
  apps/group/schema/group.py
  apps/summary/api.py
  apps/summary/services/gemini_service.py
  apps/usage/api/schemas.py
  apps/users/api/endpoints.py
Labels: 윤석, ✨ Feature, 🛠 Fix

#20 feat: pydantic-logfire 연동하기
  .env.example
  .github/workflows/deploy.yaml
  config/asgi.py
  config/settings/base.py
  config/wsgi.py
  pyproject.toml
  uv.lock
Labels: 윤석, ✨ Feature
